### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by iwensu0313** [iwensu0313/aqculture-data#4]
## Jan 25 - 31, 2019
Finalize the following before publishing next
- [ ] Visuals in FDA import refusals
- [x] Content for each section
- [ ] Download and integrate more NOAA CA seafood import (prior to 2014)
